### ISSUE TITLE
Implement the web front-end for storing recipes.

### ISSUE THREAD

**Issue by cakir-enes** [cakir-enes/gastrogang-web#1]
Definition of done:
- Show error message for empty required fields.
- If user attempts to store a recipe with already existing name show error.

**Comment by bur-k** [comment]
[done] Show error message for empty required fields.
[todo] If user attempts to store a recipe with already existing name show error.

**Comment by bur-k** [comment]
fdec184ac325348718b14af391d6c5a454f5a29e
