### ISSUE TITLE
Implement frontend for login/signup.

### ISSUE THREAD

**Issue by cakir-enes** [cakir-enes/gastrogang-web#11]
Definition of done:
- A form for username and password.
- Password should be at least 6 chars long
- If user attempts logging in with a wrong password, show error msg

**Comment by bur-k** [comment]
9ce5f8a8decca35fde28e4e5c5ea96d1fa8a6901
521b331852383cc641f0f5191ad5d075f002b880
5d31b439b4a5fc31932e8b736f0eb8d85422e57f
